# Created with WinGet Automation using Komac v1.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: SatoshiLabs.trezor-suite
PackageVersion: 23.11.3
PackageLocale: en-US
Publisher: SatoshiLabs
PublisherUrl: https://github.com/trezor
PublisherSupportUrl: https://github.com/trezor/trezor-suite/issues
Author: trezor
PackageName: Trezor Suite
PackageUrl: https://github.com/trezor/trezor-suite
License: TREZOR REFERENCE SOURCE LICENSE (T-RSL)
LicenseUrl: https://github.com/trezor/trezor-suite/blob/develop/LICENSE.md
ShortDescription: Trezor Suite desktop application
Tags:
- bitcoin
- electron
- suite
- trezor
- wallet
ReleaseNotes: |-
  ğŸš€ New features
  - Weâ€™ve made it even easier for you to access the Buy, Sell, and Exchange features within your accounts, providing a more streamlined user experience.
  ğŸ¨ Improvements
  - Weâ€™re pleased to announce that French has been added as a new official language, making Trezor Suite more inclusive and accessible to a broader audience.
  - Weâ€™ve eliminated redundant confirmation notifications, reducing unnecessary interruptions and making your user experience more efficient.
  ğŸ”§ Bug fixes
  - On Linux, resolved crashing of the app immediately after start up.
  - The â€œUpdate on quitâ€ button will now exit the application when intended, ensuring a smoother user experience.
  - Weâ€™ve resolved the issue with coin icons on MacOS 14, so they now appear correctly and consistently in the app.
ReleaseNotesUrl: https://github.com/trezor/trezor-suite/releases/tag/v23.11.3
ManifestType: defaultLocale
ManifestVersion: 1.5.0
